### ISSUE TITLE
Question: Expansion 

### ISSUE THREAD

**Issue by sevmardi** [remigiusz-suwalski/programming-cheatsheets#6]
First of all thanks for taking the time and making this. 

Just a quick question. Are you planning to expand this by adding some other programming languages? 

Cheers :+1:

**Comment by remigiusz-suwalski** [comment]
First I would like to complete the cheatsheets that are already here. Later I plan to develop C++, Mathematica, Perl and Ruby notes. If you know a language, just create a fork, write anything you want in a separate folder with language name and make a pull request.

**Comment by sevmardi** [comment]
Thanks! Will do.
