### ISSUE TITLE
! Undefined control sequence.

### ISSUE THREAD

**Issue by mogoh** [remigiusz-suwalski/programming-cheatsheets#9]
I am getting this Error while compiling bash/bash.tex

Am I missing any dependencies?
```
...
(/usr/share/texlive/texmf-dist/tex/latex/mweights/mweights.sty)
! Undefined control sequence.
<argument> \mdseries@rm 
                        
l.280   \rmfamily
                 
? 
```

**Comment by remigiusz-suwalski** [comment]
A clean install of Antergos 17.2 with vanilla texlive and *pygmentize* included compile without problems, one has to execute `pdflatex -shell-escape bash.tex`  in the `bash `directory.

**Comment by mogoh** [comment]
OK, it looks like a bug in the Alegreya package, witch is, as far as I can see, fixed and in the upcomming version of texlive-fonts-extra of Ubuntu.

So this can be closed.

**Comment by remigiusz-suwalski** [comment]
You can comment out the \usepackage{Alegreya} line and break the layout... LaTeX users are encouraged to use the vanilla texlive, as it's more up to date. If you don't want to, just wait.
